//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.APP_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.DoctorBookings = new HashSet<DoctorBooking>();
            this.DoctorBookings1 = new HashSet<DoctorBooking>();
            this.DoctorBookings2 = new HashSet<DoctorBooking>();
            this.PackagePurchasedInvoices = new HashSet<PackagePurchasedInvoice>();
            this.PackageUsedHistories = new HashSet<PackageUsedHistory>();
            this.PurchasedPackageSharers = new HashSet<PurchasedPackageSharer>();
            this.PurchasedPackageSharers1 = new HashSet<PurchasedPackageSharer>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Name { get; set; }
        public string PhoneNumber { get; set; }
        public string Address { get; set; }
        public string NRC { get; set; }
        public string Email { get; set; }
        public Nullable<int> CityId { get; set; }
        public string TownShip { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<int> MemberTypeID { get; set; }
        public string VIPMemberId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string CustomerCode { get; set; }
        public Nullable<int> CustomerTypeId { get; set; }
        public Nullable<System.DateTime> PromoteDate { get; set; }
        public string Maritalstatus { get; set; }
        public string EmergencyContactPhone { get; set; }
        public string EmergencyContactName { get; set; }
        public string Relationship { get; set; }
        public string MainConcern { get; set; }
        public string MedicalHistory { get; set; }
        public string DrugAllergy { get; set; }
        public string ProfilePath { get; set; }
        public string Remark { get; set; }
        public Nullable<int> ReferredID { get; set; }
    
        public virtual City City { get; set; }
        public virtual MemberType MemberType { get; set; }
        public virtual ICollection<DoctorBooking> DoctorBookings { get; set; }
        public virtual ICollection<DoctorBooking> DoctorBookings1 { get; set; }
        public virtual ICollection<DoctorBooking> DoctorBookings2 { get; set; }
        public virtual ICollection<PackagePurchasedInvoice> PackagePurchasedInvoices { get; set; }
        public virtual ICollection<PackageUsedHistory> PackageUsedHistories { get; set; }
        public virtual ICollection<PurchasedPackageSharer> PurchasedPackageSharers { get; set; }
        public virtual ICollection<PurchasedPackageSharer> PurchasedPackageSharers1 { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
