//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.APP_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorBooking
    {
        public string DoctorBookingId { get; set; }
        public int PatientId { get; set; }
        public int DoctorId { get; set; }
        public string DoctorScheduleId { get; set; }
        public int AssistNurseId { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string FromTime { get; set; }
        public string ToTime { get; set; }
        public string Day { get; set; }
        public string BookingCase { get; set; }
        public long PackageId { get; set; }
        public bool IsBook { get; set; }
        public bool IsConfirm { get; set; }
        public bool IsDelete { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedUserId { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedUserId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Customer Customer1 { get; set; }
        public virtual Customer Customer2 { get; set; }
        public virtual DoctorSchedule DoctorSchedule { get; set; }
        public virtual Product Product { get; set; }
    }
}
