//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.APP_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorSchedule
    {
        public DoctorSchedule()
        {
            this.DoctorBookings = new HashSet<DoctorBooking>();
        }
    
        public string DoctorScheduleId { get; set; }
        public int DoctorId { get; set; }
        public bool Mon { get; set; }
        public bool Tue { get; set; }
        public bool Wed { get; set; }
        public bool Thu { get; set; }
        public bool Fri { get; set; }
        public bool Sat { get; set; }
        public bool Sun { get; set; }
        public string FromTime { get; set; }
        public string ToTime { get; set; }
        public bool IsDelete { get; set; }
        public int UserId { get; set; }
    
        public virtual ICollection<DoctorBooking> DoctorBookings { get; set; }
    }
}
