//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.APP_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackagePurchasedInvoice
    {
        public PackagePurchasedInvoice()
        {
            this.PackageUsedHistories = new HashSet<PackageUsedHistory>();
            this.PurchasedPackageSharers = new HashSet<PurchasedPackageSharer>();
        }
    
        public string PackagePurchasedInvoiceId { get; set; }
        public long TransactionDetailId { get; set; }
        public int CustomerId { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public long ProductId { get; set; }
        public int UseQty { get; set; }
        public bool IsDelete { get; set; }
        public int UserId { get; set; }
        public Nullable<int> packageFrequency { get; set; }
        public bool IsCancelled { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
        public virtual TransactionDetail TransactionDetail { get; set; }
        public virtual ICollection<PackageUsedHistory> PackageUsedHistories { get; set; }
        public virtual ICollection<PurchasedPackageSharer> PurchasedPackageSharers { get; set; }
    }
}
