//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.APP_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetProcedureProduct
    {
        public int Id { get; set; }
        public long ProcedureProductID { get; set; }
        public string ProcedureProductName { get; set; }
        public long ProductID { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> ProductQty { get; set; }
    }
}
