//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.APP_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitConversionHeader
    {
        public UnitConversionHeader()
        {
            this.UnitConversionDetails = new HashSet<UnitConversionDetail>();
        }
    
        public int Id { get; set; }
        public int FromProductId { get; set; }
        public int FromQty { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
    
        public virtual ICollection<UnitConversionDetail> UnitConversionDetails { get; set; }
    }
}
