//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.APP_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitConversionDetail
    {
        public int Id { get; set; }
        public int UnitConversionHeaderId { get; set; }
        public int FromProductId { get; set; }
        public int ToProductId { get; set; }
        public int ToQty { get; set; }
    
        public virtual UnitConversionHeader UnitConversionHeader { get; set; }
    }
}
